### ISSUE TITLE
Add styles for markdown headings

### ISSUE THREAD

**Issue by cferdinandi** [zoxon/vscode-theme-monokai-light#2]
Hi there! Thanks for creating this theme... it's 99.9% perfect! The only thing missing is styles for markdown headings.

These can be included by adding the following to theme.json file:

```json
{
	"name": "Markup Headings",
	"scope": "markup.heading",
	"settings": {
		"foreground": "#cf7000"
	}
},
{
	"name": "Markup Setext Header",
	"scope": "markup.heading.setext",
	"settings": {
		"fontStyle": "",
		"foreground": "#cf7000"
	}
},
```

I can submit this is a pull request if you'd like?

**Comment by zoxon** [comment]
Thank you! Please make pull request.
